module.exports = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Part 1 — Tokenization',
      items: [
        'part-1-tokenization/chapter-1-why-tokenization-matters',
        'part-1-tokenization/chapter-2-strings-unicode-and-bytes',
        'part-1-tokenization/chapter-3-byte-pair-encoding',
        'part-1-tokenization/chapter-4-training-a-tokenizer',
        'part-1-tokenization/chapter-5-encoding-and-decoding',
        'part-1-tokenization/chapter-6-regex-pre-tokenization',
        'part-1-tokenization/chapter-7-gpt-tokenizers-and-special-tokens',
        'part-1-tokenization/chapter-8-quirks-and-future',
      ],
    },
    {
      type: 'category',
      label: 'Part 2 — Transformer',
      items: [
        'part-2-transformer/chapter-1-building-the-dataset',
        'part-2-transformer/chapter-2-the-bigram-baseline',
        'part-2-transformer/chapter-3-efficient-context-mixing',
        'part-2-transformer/chapter-4-self-attention',
        'part-2-transformer/chapter-5-multi-head-attention',
        'part-2-transformer/chapter-6-transformer-block',
      ],
    },
    {
      type: 'category',
      label: 'Part 3 — Train a GPT',
      items: [
        'part-3-train-a-gpt/chapter-1-reproducing-gpt-2',
        'part-3-train-a-gpt/chapter-2-implementing-the-gpt-2-model',
        'part-3-train-a-gpt/chapter-3-loading-the-gpt-2-checkpoint',
        'part-3-train-a-gpt/chapter-4-forward-pass-and-logits',
        'part-3-train-a-gpt/chapter-5-tokenization-and-sampling',
        'part-3-train-a-gpt/chapter-6-training-batches-and-cross-entropy',
        'part-3-train-a-gpt/chapter-7-optimization-loop-and-data-loading',
        'part-3-train-a-gpt/chapter-8-parameter-sharing-and-initialization',
        'part-3-train-a-gpt/chapter-9-making-training-fast',
        'part-3-train-a-gpt/chapter-10-precision-compilation-and-flash-attention',
        'part-3-train-a-gpt/chapter-11-hardware-friendly-model-shapes',
        'part-3-train-a-gpt/chapter-12-training-hyperparameters-and-schedules',
        'part-3-train-a-gpt/chapter-13-gradient-accumulation-and-ddp',
        'part-3-train-a-gpt/chapter-14-datasets-validation-and-evaluation',
        'part-3-train-a-gpt/chapter-15-results-and-summary',
      ],
    },
  ],
};
